### ISSUE TITLE
Benchmark results are not available

### ISSUE THREAD

**Issue by melvi-l** [ivangfr/graalvm-quarkus-micronaut-springboot#27]
Hello, 

Could you please make your results publicly available? Medium requires a membership to access your article.

Thanks a lot !

**Comment by ivangfr** [comment]
Hi @melvi-l,

Thank you for reaching out.

I started this project five years ago, with the first commit made on October 14, 2019. Since then, despite my continuous work on upgrading and maintaining the applications, I haven't received any support through GitHub Sponsorship.

Given the ongoing effort I've put into this project, I decided to move the results to Medium articles, where I hope to gain some recognition and compensation for my work.

Feel free to connect with me on LinkedIn, and we can continue the conversation there.

Best regards,
